const ShopActionTypes = {
  FETCH_SHOP_DATA_START: "FETCH_SHOP_DATA_START",
  FETCH_SHOP_DATA_SUCCESS: "FETCH_SHOP_DATA_SUCCESS",
  FETCH_SHOP_DATA_FAILURE: "FETCH_SHOP_DATA_FAILURE",
  FETCH_SHOP_SETTINGS_START: "FETCH_SHOP_SETTINGS_START",
  FETCH_SHOP_SETTINGS_SUCCESS: "FETCH_SHOP_SETTINGS_SUCCESS",
  FETCH_SHOP_SETTINGS_FAILURE: "FETCH_SHOP_SETTINGS_FAILURE",
};

export default ShopActionTypes;
