const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  UPDATE_ITEM_WITH_INPUT: "UPDATE_ITEM_WITH_INPUT",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionTypes;
